### ISSUE TITLE
Add a Performance Profiler to display data in graphical format.

### ISSUE THREAD

**Issue by SahilTara** [BabylonJS/Babylon.js#10566]
## Description
This issue will be used to track the progress of the performance profiler feature.
Basically the goal is to enhance the experience of people who would like to figure out where performance issues are arising.
This will be done by allowing users to plot data over time for a variety of things such as fps, draw calls, number of active meshes, frame time. As this feature evolves more and more data sources will be added :D.

A bit of a rough visual for what I'm trying to build. Of course disclaimer that design is subject to change (and will change) this is just to illustrate what I'm trying to build.
![image](https://user-images.githubusercontent.com/32103099/123318358-1dff0a00-d4fd-11eb-800f-7d594dec7498.png)

This tool is going to be able to get engine specific data which chrome dev tools is currently not able to do.

We will be using a pop out format similar to the animation curve editor for the desktop flow, while mobile will have to record, export, then import on to the desktop.

I have made a list of milestones to cover for my internship (right now they are really rough and based on the information I know so they are subject to change around, and will continue to gain higher fidelity as I get closer to the milestone). If you've seen the [forum link](https://forum.babylonjs.com/t/babylon-performance-profiler/21826) you may notice the milestones below have already changed due to a better understanding of the requirements. 

## Milestone 1:

- [x] Ask team about what “data sources” they would like to see 
- [x] Ask community about what “data sources” they would like to see
- [x] Develop a list of data sources to be implemented.

## Milestone 2: 

- [x] Create button to open profiler
- [x] Have a pop up that displays a canvas 
- [x] Use the canvas API to create a line graph (single line)
  - [x] 	Draw axis (that dynamically adjusts to data)
  - [x] 	Draw data points
- [x] Implement graph scrolling 
- [x] Test graph with live data (can be something as simple as FPS counter)

## Milestone 3:

- [x] Allow for zooming into the graph
- [x] Allow for panning of the graph
- [x] Allow for hovering over data points and displaying the actual values.
- [x] Allow for custom colourization for lines.
- [x] Allow rescaling of window.
- [x] Allow for toggling of data sources

## Milestone 4:
- [x] Allow for the collection of performance data. 
- [x] Begin collecting FPS data.
- [x] Connect the graph to the collector.
- [x] Have tickers update with relevant info on the right side bar as in image.
- [x] Normalization of data

## Milestone 5:

- [x] Allow for the collection of draw calls, number of active meshes, frame time.
- [x] Allow displaying of draw calls, number of active meshes, frame time within the graph.
- [x] Add our performance collector as a scene extension so that the playground and inspector can share a performance collector. 
- [x] Allow for recording of data.
- [x] Allow for exporting of data to csv.
- [x] Allow for loading of data from csv.
- [x] Allow for user defined tracking of data. (This task was finished due to related work in Milestone 4 and 5).
- [x] Allow collection for everything else under the counter and frame steps duration under statistics (was a stretch goal but was easy to implement).

## Milestone 6:
- [x] Draw a vertical line where the mouse currently is, with a triangle acting as a pointer.
- [x] Move the tooltip lower, closer to the axis instead of at 50% of the graph height.
- [x] Draw a square box where the numbers are to make the numbers pop more.
- [x] Allow plotting of custom “events”
- [x] Connect cpu usage (compute pressure) to the graph.

## Milestone 7:
- [x] Convert the current time in ms to be ms, s, minutes... etc
- [x] Add a go back to live button.
- [x] Group all the buttons inside of an "accordion" component like how the count and frame steps are. 
- [x] Allow hovering over a single line which changes the opacity of the other lines.

## Milestone 8:

- [x] Documentation!

## Possible Stretch Goals:
- Figure out how to do down sampling if perf is degraded too much (LTTB algorithm) 
- Implement updated sidebar design.
- Allow for user defined “Region” for profiling (collect fps and all that between start and end). (May not make sense to be done, needs discussion).
- Memory usage
- Minimap for displaying data so far
- Allow for displaying the data in graphs in the scene itself
- Create a better experience for mobile
- Web worker to process data

**Comment by sebavan** [comment]
Can not wait !!!! :-)

**Comment by RaananW** [comment]
That's gonna be awesome :-)

You can reference this issue in related PRs so everyone can track the progress.

**Comment by RaananW** [comment]
Closing this as all tasks are done. Thanks @SahilTara for the wonderful work! Pinging @msDestiny14 FYI
