### ISSUE TITLE
[GE Visual Bug] Hover/selected states on tree view do not match design

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Babylon.js#10741]
There are several types of hover state for controls in the tree view. Some of those states are incorrect in the current implementation. Here are the correct states. 

- [ ] control selected: background color #bfbebe

![image](https://user-images.githubusercontent.com/31326855/126847931-e0cffc57-7f55-4bcc-8ed3-0c49be42e072.png)

- [ ] control selected and hovered: background color #bfbebe, outline #527089, show make component and visibility buttons

![image](https://user-images.githubusercontent.com/31326855/126847969-706991d1-775c-456c-a468-6b618f460997.png)

- [ ] one control selected while hovering another control: selected control as above, hovered control with outline #527089 and showing make component and visibility buttons

![image](https://user-images.githubusercontent.com/31326855/126848118-e6bafc2e-505d-4551-b2f0-65b473130d93.png)

- [ ] selected control being dragged to reorder/parent: control in original position with selected background as above, moving name of control only at 70% opacity, line showing where control will drop if released using #527089

![image](https://user-images.githubusercontent.com/31326855/126848300-332688cd-691a-4367-a7f3-04456dbe6872.png)

- [ ] selected control being dragged to drop on container to make child: control in original position with selected background as above, moving name only as above, hovered container with #ffffff background and make child icon colored #333333 and right justified. Note that in this hover state, we do not show the make component or the visibility buttons as the mouse is already in a down state due to the drag action.

![image](https://user-images.githubusercontent.com/31326855/126848326-9129fb40-2cf0-4ed7-9ca6-3bae676a1e61.png)
