### ISSUE TITLE
User Device Input Path

### ISSUE THREAD

**Issue by PolygonalSun** [BabylonJS/Babylon.js#12566]
# User Device Input Path
## Tasks:
- [x] Milestone 1 – Full Pointer Support in Native
  - ~Update NativeInput to Handle New Pointers~
  - ~Mouse Implementation~
    - ~Win32~
    - ~UWP~
    - ~MacOS~
    - ~Linux (X11)~
  - ~Touch Implementation~
    - ~Win32~
    - ~UWP~
    - ~iOS~
    - ~Android~

- [x] Milestone 2 – Build up Testing Platform (Tracked in https://github.com/BabylonJS/Babylon.js/issues/12661)
  - ~Create Test Environment with Necessary Mock Objects~
  - ~Create Unit Tests to Test Input System on JS~
  - ~Integrate Safari testing into CI~
  - ~Convert Babylon Native to use Jest~
  - ~Create Input Recorder~ (Removing from Milestone)

- [ ] Milestone 3 – Performance and Stability Improvements (Tracked in https://github.com/babylonjs/babylon.js/issues/12898)
  - Improve Input Perf (frame call reduction)
  - ~Clean up and flatten Input enum/file structure~
  - ~Move Browser-Specific Logic into `DeviceInputSystem` for more uniform cross-browser experience~
  - Implement Lazy Picking (Turn on/instantiate picking elements when picking is first explicitly used)

- [ ] Milestone 4 – Keyboard Support in Native- Update NativeInput to Handle Keyboards: Pre-lim keyboard work is in draft [PR](https://github.com/BabylonJS/BabylonNative/pull/1042)
  - Update NativeInput to Handle Keyboard Input
  - Keyboard Implementation
    - Win32
    - UWP
    - Linux
    - MacOS
  - Add Testing for Keyboard (and focus, potentially)

## Bugs:

**Comment by PolygonalSun** [comment]
Status as of 5/20:
Win32 Implemenation (Keyboard): In Draft https://github.com/BabylonJS/BabylonNative/pull/1042
UWP Implemenation (Keyboard): In Draft https://github.com/BabylonJS/BabylonNative/pull/1042
Linux Implemenation (Keyboard): Building Keycode Conversion Table
MacOS Implemenation (Keyboard): Investigating issue where event isn’t firing properly

pointerUpPredicate not working/unable to disable up pick (https://github.com/BabylonJS/Babylon.js/pull/12524)
Multiple Canvases causing crash - User is attempting to produce repro ([Forum Link](https://forum.babylonjs.com/t/multiple-canvases-causing-crash/28493/12))

**Comment by PolygonalSun** [comment]
Status as of 5/20:
Create custom mock window object for testing input and events: Working on window, testing for missing logic
Create Unit Tests to Test Input System on JS: Started writing tests and finding all test cases

Win32 Implemenation (Keyboard): In Draft PR: https://github.com/BabylonJS/BabylonNative/pull/1042
UWP Implemenation (Keyboard): In Draft PR: https://github.com/BabylonJS/BabylonNative/pull/1042
Linux Implemenation (Keyboard): Building Keycode Conversion Table
MacOS Implemenation (Keyboard): Investigating issue where event isn’t firing properly

Multiple Canvases causing crash - User is attempting to produce repro

**Comment by PolygonalSun** [comment]
Status as of 6/3:
Create custom mock window object for testing input and events: Identified object gaps, beginning environment implementation
Create Unit Tests to Test Input System on JS: Prototyped tests for baseline, will refine tests as environment implementation is completed

Win32 Implemenation (Keyboard): In Draft PR: https://github.com/BabylonJS/BabylonNative/pull/1042
UWP Implemenation (Keyboard): In Draft PR: https://github.com/BabylonJS/BabylonNative/pull/1042
Linux Implemenation (Keyboard): Building Keycode Conversion Table
MacOS Implemenation (Keyboard): Investigating issue where event isn’t firing properly

Multiple Canvases causing crash - User is attempting to produce repro

**Comment by thomlucc** [comment]
Closing as it is now tracked as a project
