### ISSUE TITLE
GLTFSerializer New Extensions' Support

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Babylon.js#12600]
Update Babylon GLTF Serializer to support more glTF features and extensions.
Some extensions, such Draco and KTX2, will require several steps to being completed.

**Milestones**:

- [x] [EXT_mesh_gpu_instancing ](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_mesh_gpu_instancing)
- [x] [Draco Compression](https://google.github.io/draco/)
  - [x] Draco Encoder ([PR](https://github.com/BabylonJS/Babylon.js/pull/12628))
  - [x] [KHR_draco_mesh_compression ](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_draco_mesh_compression/README.md)
- [ ] [KTX2 Compression](http://github.khronos.org/KTX-Specification/)
  - [ ] KTX2 Encoder
  - [ ] [KHR_texture_basisu](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_texture_basisu/README.md)

**Comment by alexchuber** [comment]
Tracking the KTX2 compression here https://github.com/BabylonJS/Babylon.js/issues/16274 and closing this.
