### ISSUE TITLE
Babylon development friction

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/Babylon.js#4267]
Small issues faced when building a large project in babylon:
BABYLON
- [x] Teleportation setup for webVR should be included in constructor (and enabling interaction)
- [x] Adding/removing nested meshes to a scene (Both methods could have option for recursive)
- [x] Getting a root mesh from a loaded 3D file is not obvious (Possibly add helper method on assetContainer) (Example needed to load 3D file and move it around)
- [x] Loading a file and needing to split the string into root and filename adds friction (Now working playground#17MXFZ#9)
- [x] Edge fails silently when loading a local file in babylon (I think babylon is eating the error)
- [x] More helper methods for webVR setup to create a nice environment/gui/3D text faster (Covered by https://github.com/BabylonJS/Babylon.js/issues/4310)
- [x] Add ability to easily drag meshes from in webVR  (Covered by https://github.com/BabylonJS/Babylon.js/issues/4141)

Docs:
- [x] More docs around creating a local babylonjs project (Figuring out how to integrate a npm packages was difficult) (Project setup exactly like playground was tricky, pep.js, create engine with stencil buffer to get vr mirroring to work, etc.)
- [x] Add to getting started docs reference to https://preview.babylonjs.com/loaders/babylon.glTFFileLoader.js
- [x] Discovering how to get started with a renderloop is not obvious in babylon (Example needed)
- [x] Search for docs similar to examples page would be helpful

**Comment by deltakosh** [comment]
Some of them will be tricky:) but a good list of improvements!

**Comment by deltakosh** [comment]
"Loading a file and needing to split the string into root and filename adds friction" is already supported actually if you specify it in the path and set the file to ""
