### ISSUE TITLE
Some bugs for gizmos

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#4623]
- [x] Make behavior and axis meshes public
- [x] The gizmo scale should not change when moving: https://www.babylonjs-playground.com/#IXNS0D#1
- [x] The green rotation torus seems to lose the control when trying to rotate it: https://www.babylonjs-playground.com/#31M2AP#7
- [x] Scaling to the smaller size reverse the position of the control cube: https://www.babylonjs-playground.com/#DEYAQ5#47
- [x] Translation with mouse (moving the box) seems weird. Does not stay on XY axis: https://www.babylonjs-playground.com/#DEYAQ5#47
 - [x] Nested meshes not working https://www.babylonjs-playground.com/#DEYAQ5#51 
 - [x] Z-drag in sixdofdrag behavior not working as expected  https://www.babylonjs-playground.com/#DEYAQ5#51

**Comment by deltakosh** [comment]
Createpickingray expects a screen coordinates so 0,0 is the upper left corner of the screen. Something more on the center of the screen should work better

**Comment by TrevorDev** [comment]
Shouldn't any screen pick's ray start at or travel through the camera's position?

**Comment by deltakosh** [comment]
nope as you are projected on near plane
